server:
  port: 7803

#jdbc
spring:
  db-mysql:
    datasource:
      jdbc-url: jdbc:mysql://localhost:4406/my_board?allowMultiQueries=true
      username: user2
      password : user2@123
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: my_board
    task:
      execution:
        pool:
          core-size: 5
          max-size: 10
          queue-capacity: 5
